### ISSUE TITLE
Crash with 21:9 and 17:9 aspect ratios

### ISSUE THREAD

**Issue by Shrimpey** [neos7/FiveM_vstancer#11]
MenuAPI's right alignment does not support 17:9 and 21:9 aspect ratios and vStancer seems to crash on initialization with those aspect ratios.

**Suggested solution** (one used in vMenu to take care of those cases):
https://github.com/Shrimpey/fivem-vstancer/commit/c1bf1958a069a95d462aad7c03fe289a83190788

**Comment by carmineos** [comment]
This has already been fixed in MenuAPI itself check this [PR](https://github.com/TomGrobbe/MenuAPI/pull/11/files) since MenuAPI shouldn't throw exceptions at all. Development branch of vstancer already uses an updated version of MenuAPI (check [f4717c9](https://github.com/carmineos/fivem-vstancer/commit/f4717c988b85b8f4c2ba0cb1ba7b0920ac10e5b6)) which fixes that so you can a development build or just pick an updated copy of the newest MenuAPI build.
I think I should just trigger a new master build :)
