### ISSUE TITLE
Option to disable key enhancement

### ISSUE THREAD

**Issue by TanguyOrtegat** [neos7/FiveM_vstancer#15]
Hi, 

Not an issue but a remark...
Maybe is a good idea to make a boolean in the config file to remove the ToggleMenuControl. Ofc we can put nothing in config file to not let it trigger, but is will alway execute the native that is not nessesary. It is great that enableing/disableing event is in the config file already. I will make it work only ls cusom can have access to the menu.

**Comment by carmineos** [comment]
With artifacts from [development branch](https://github.com/carmineos/fivem-vstancer/tree/development) you can choose to:
* Assign -1 as ToggleMenuControl so it doesn't toggle with any control
* Expose the event to toggle the menu
* Expose the command to toggle the menu
* Disable the menu completely (no instance is created at all) and use exports API to edit values from you own script/ui

I know that in order to have a strong permissions system it needs to have a server side script, that's something I'll add for the future but I'm not focusing on it right now.
A workaround could be implementing permissions in your own script/ui and use exports to do what you want.

**Comment by TanguyOrtegat** [comment]
okay i ll have a look into it. Thanks for your reply
